namespace Jcd.Reflection.Tests._Fakes.TypesTest;

public class Int64DerivedFromIImplementsIDerivedFromIiDerivedFromIGenericBase : IDerivedFromIiDerivedFromIImplementsIDerivedFromIiDerivedFromIGenericBase<int>
{
}